Repository zanfranceschi/rinha-de-backend-2024-q1, pull requests merged in 2024-02, with the labels that each got.

#47 Enviar submissão leoralph
  participantes/leoralph/COISA_RUIM.jpeg
  participantes/leoralph/README.md
  participantes/leoralph/docker-compose.yml
  participantes/leoralph/init.sql
  participantes/leoralph/nginx.conf
  participantes/leoralph/postgresql.conf
Labels: invalid

#132 chore: tunning configs of previous submission
  participantes/omurilo/docker-compose.yaml
  participantes/omurilo/nginx.conf
Labels: invalid

#239 feat: add bun api
  participantes/jonattas_bunjs/README.md
  participantes/jonattas_bunjs/docker-compose.yml
  participantes/jonattas_bunjs/nginx.conf
  participantes/jonattas_bunjs/schema.sql
Labels: invalid

#348 Versão nova de .NET do Giovanni
  participantes/giovannibassi-nonpooled/README.md
  participantes/giovannibassi-nonpooled/docker-compose.yml
  participantes/giovannibassi-nonpooled/envoy.yaml
  participantes/giovannibassi-nonpooled/sql/criartransacao.sql
  participantes/giovannibassi-nonpooled/sql/ddl.sql
  participantes/giovannibassi-nonpooled/sql/resetdb.sql
Labels: new submission

#351 participação nielson rolim - ror app
  participantes/nielsonrolim-ror/README.md
  participantes/nielsonrolim-ror/docker-compose.yml
  participantes/nielsonrolim-ror/nginx.conf
Labels: new submission

#352 Add participação - antoniogdelrio
  participantes/antoniogdelrio/README.md
  participantes/antoniogdelrio/docker-compose.yml
  participantes/antoniogdelrio/nginx.conf
  participantes/antoniogdelrio/postgresql.conf
  participantes/antoniogdelrio/script.sql
Labels: new submission

#354 feat: coloca meu denogalo para brigar
  participantes/deno-cassiogangrel/README.md
  participantes/deno-cassiogangrel/docker-compose.yml
  participantes/deno-cassiogangrel/init.sql
  participantes/deno-cassiogangrel/nginx.conf
Labels: new submission

#356 feat: add italobbarros project
  participantes/italobbarros/README.md
  participantes/italobbarros/docker-compose.yml
  participantes/italobbarros/makefile
  participantes/italobbarros/nginx.conf
  participantes/italobbarros/sql/postgresql.conf
  participantes/italobbarros/sql/script.sql
Labels: new submission

#357 Adicionando o meu projeto (Cesar Rodrigues)
  participantes/cesar-rodrigues/README.md
  participantes/cesar-rodrigues/database/mongo-init.js
  participantes/cesar-rodrigues/docker-compose.yml
  participantes/cesar-rodrigues/nginx/nginx.conf
Labels: new submission

#360 Submissão - Rodrigo Caldeira - C
  participantes/rodrigocaldeira-c/README.md
  participantes/rodrigocaldeira-c/docker-compose.yml
  participantes/rodrigocaldeira-c/init.sql
  participantes/rodrigocaldeira-c/nginx.conf
Labels: new submission

#347 feat: update nginx conf and remove testada
  participantes/halexv/docker-compose.logs
  participantes/halexv/nginx.conf
  participantes/halexv/testada
Labels: retest

#349 Mudança nas variáveis de ambiente
  participantes/gabrielfmagalhaes/docker-compose.yaml
  participantes/gabrielfmagalhaes/testada
Labels: retest

#350 re-testing
  participantes/jpaf/testada
Labels: retest

#358 alterando tabelas
  participantes/jojodev/init.sql
Labels: retest

#359 Delete participantes/jojodev/testada
  participantes/jojodev/testada
Labels: retest

#361 fix docker-compose and adding SQL file
  participantes/avinho/docker-compose.yml
  participantes/avinho/import.sql
  participantes/avinho/testada
Labels: retest

#362 fix: pointing to amd64 image
  participantes/rhsobr-bun/docker-compose.yml
  participantes/rhsobr-bun/testada
Labels: retest

#381 feat: includes new participant
  participantes/cristiano182/README.md
  participantes/cristiano182/docker-compose.yml
  participantes/cristiano182/nginx.conf
Labels: invalid

#425 Submissão: Node minimal api - itujo
  participantes/itujo-minimal-node-uws/README.md
  participantes/itujo-minimal-node-uws/docker-compose.yml
  participantes/itujo-minimal-node-uws/init.sql
  participantes/itujo-minimal-node-uws/nginx.conf
  participantes/itujo-minimal-node-uws/postgresql.conf
Labels: new submission

#423 submit v1: 1garo
  participantes/1garo/README.md
  participantes/1garo/docker-compose.yml
  participantes/1garo/init.sql
  participantes/1garo/nginx.conf
Labels: new submission

#422 stack dotnet aot
  participantes/fabionaspolini/README.md
  participantes/fabionaspolini/docker-compose.yml
  participantes/fabionaspolini/init.sql
  participantes/fabionaspolini/nginx.conf
Labels: new submission

#420 add participant my_way
  participantes/my_way/README.md
  participantes/my_way/config/nginx.conf
  participantes/my_way/config/postgresql.conf
  participantes/my_way/config/script.sql
  participantes/my_way/docker-compose.yml
Labels: retest

#419 nova versao
  participantes/lucianovilela/docker-compose.yml
  participantes/lucianovilela/nginx.conf
Labels: retest

#417 adds me
  participantes/leonardovee/README.md
  participantes/leonardovee/docker-compose.yml
  participantes/leonardovee/haproxy.cfg
  participantes/leonardovee/init.sql
Labels: new submission

#414 add participante - WilliamMaia
  participantes/williammaia/README.md
  participantes/williammaia/docker-compose.yml
  participantes/williammaia/nginx.conf
  participantes/williammaia/schema.sql
Labels: invalid, new submission

#539 atualiza script de teste para testar consistencia…
  load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala
Labels: enhancement

#612 feat: tentando baixar p75
  participantes/mateusdeitos-node/docker-compose.logs
  participantes/mateusdeitos-node/docker-compose.yml
  participantes/mateusdeitos-node/init.sql
Labels: conflito

#715 -participando!
  participantes/rodrixl/Dockerfile
  participantes/rodrixl/README.md
  participantes/rodrixl/docker-compose-local.yml
  participantes/rodrixl/docker-compose.yml
  participantes/rodrixl/nginx.conf
  participantes/rodrixl/requirements.txt
  participantes/rodrixl/script.sql
Labels: invalid
