Repository zanfranceschi/rinha-de-backend-2024-q1, pull requests merged in 2024-03, with the labels that each got.

#1130 Submissão rinha V1
  participantes/maxel-uds/README.md
  participantes/maxel-uds/docker-compose.yml
  participantes/maxel-uds/init.sql
  participantes/maxel-uds/nginx.conf
Labels: invalid

#1138 added TCP_NODELAY
  participantes/vkobinski/postgres.conf
  participantes/vkobinski/testada
Labels: conflito

#1145 Retirar minha submissão inativa da lista
  participantes/jonathanperis/README.md
  participantes/jonathanperis/testada
Labels: invalid

#1227 execução de testes
  .github/pull_request_template.md
  participantes/heitor-jsr/README.md
  participantes/heitor-jsr/data/init.sql
  participantes/heitor-jsr/docker-compose.yml
  participantes/heitor-jsr/nginx.conf
Labels: invalid

#1581 Submissao para Rinha de Backend - 2024/Q1 Joao Bittencourt - Php
  participantes/joaobittencourt-php/README.md
  participantes/joaobittencourt-php/docker-compose.yml
  participantes/joaobittencourt-php/init.sql
  participantes/joaobittencourt-php/nginx.conf
  participantes/joaobittencourt-php/php.ini
  participantes/joaobittencourt-php/postgresql.conf
Labels: invalid

#1584 Contribuição do jrkessl
  participantes/jrkessl/README.md
  participantes/jrkessl/docker-compose.yml
  participantes/jrkessl/nginx.conf
Labels: invalid

#1669 acerto memoria
  participantes/leandroaa/docker-compose.yml
Labels: conflito

#1681 Implements my version Guimadev
  participantes/guimadev-kotlin/README.md
  participantes/guimadev-kotlin/docker-compose.yml
  participantes/guimadev-kotlin/nginx.conf
  participantes/guimadev-kotlin/postgresql.conf
  participantes/guimadev-kotlin/script.sql
Labels: fora do prazo

#1682 faltou o push da imagem
  participantes/schrammel-bun-prisma/testada
Labels: fora do prazo
